# Generated by Django 5.0.7 on 2024-08-25 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='models',
            name='image',
            field=models.ImageField(default='chais/default.jpg', upload_to='chais/'),
        ),
        migrations.AddField(
            model_name='models',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('BT', 'BLACK TEA')], default='ML', max_length=2),
        ),
    ]
