# Generated by Django 5.0.7 on 2024-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0002_models_date_added_models_image_models_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='models',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
